import pyautogui
import time
pyautogui.press('win')
pyautogui.write('excel')
pyautogui.press('enter')
time.sleep(2)
pyautogui.click(x=362, y=262)
time.sleep(1)
pyautogui.click(x=172, y=155)
pyautogui.write('Produto final')
pyautogui.press('enter')
pyautogui.write('Categoria')
pyautogui.press('enter')
pyautogui.write('Marca')
pyautogui.press('enter')
pyautogui.write('Preço')
pyautogui.press('enter')
pyautogui.write('Modelagem')
pyautogui.press('enter')
pyautogui.write('Codigo')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.write('Categoria')
pyautogui.press('enter')
pyautogui.write('Marca')
pyautogui.press('enter')
pyautogui.write('Preço')
pyautogui.press('enter')
pyautogui.write('Modelagem')
pyautogui.press('enter')
pyautogui.write('Codigo')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.write('Categoria')
pyautogui.press('enter')
pyautogui.write('Marca')
pyautogui.press('enter')
pyautogui.write('Preço')
pyautogui.press('enter')
pyautogui.write('Modelagem')
pyautogui.press('enter')
pyautogui.write('Codigo')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.write('Categoria')
pyautogui.press('enter')
pyautogui.write('Marca')
pyautogui.press('enter')
pyautogui.write('Preço')
pyautogui.press('enter')
pyautogui.write('Modelagem')
pyautogui.press('enter')
pyautogui.write('Codigo')
pyautogui.press('enter')
pyautogui.press('enter')
pyautogui.write('Categoria')
pyautogui.press('enter')
pyautogui.write('Marca')
pyautogui.press('enter')
pyautogui.write('Preço')
pyautogui.press('enter')
pyautogui.write('Modelagem')
pyautogui.press('enter')
pyautogui.write('Codigo')
pyautogui.press('enter')

pyautogui.write('Categoria')
pyautogui.press('tab')
pyautogui.write('Marca')
pyautogui.press('tab')
pyautogui.write('Preço')
pyautogui.press('tab')
pyautogui.write('Modelagem')
pyautogui.press('tab')
pyautogui.write('Codigo')


